# Generated by Django 5.2.3 on 2025-06-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_feuille', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Donnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne', models.CharField(max_length=255)),
                ('colonne', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('valeur', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.categorie')),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.tableau')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_theme', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='tableau',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.theme'),
        ),
    ]
