# Generated by Django 5.2.3 on 2025-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donnees',
            name='statut',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
