# Generated by Django 5.2.3 on 2025-08-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donnees',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donnees',
            name='ordre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donnees',
            name='parent_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
