# Generated by Django 5.2.3 on 2025-10-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0002_donnees_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donnees',
            name='valeur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
