# Generated by Django 5.2.3 on 2025-10-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0002_donnees_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnees',
            name='statut',
        ),
    ]
