# Generated by Django 5.2.3 on 2025-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0003_alter_donnees_statut_alter_donnees_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='donnees',
            name='note_colonne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
