# Generated by Django 5.2.3 on 2025-08-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0003_donnees_code_donnees_ordre_donnees_parent_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnees',
            name='code',
        ),
        migrations.RemoveField(
            model_name='donnees',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='donnees',
            name='parent_code',
        ),
        migrations.AlterField(
            model_name='donnees',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donnees',
            name='unite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='LigneIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=100, null=True)),
                ('ordre', models.IntegerField(blank=True, null=True)),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.tableau')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterField(
            model_name='donnees',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.ligneindicateur'),
        ),
    ]
