# Generated by Django 5.2.3 on 2025-10-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0003_remove_donnees_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='donnees',
            name='statut',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
