# Generated by Django 5.2.3 on 2025-08-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0004_remove_donnees_code_remove_donnees_ordre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ansade_app.ligneindicateur'),
        ),
        migrations.AlterField(
            model_name='donnees',
            name='source',
            field=models.TextField(blank=True, default='Inconnue'),
            preserve_default=False,
        ),
    ]
