# Generated by Django 5.2.3 on 2025-10-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0004_donnees_note_colonne'),
        ('ansade_app', '0004_donnees_statut'),
    ]

    operations = [
    ]
