# Generated by Django 5.2.3 on 2025-11-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0004_donnees_note_colonne'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableau',
            name='date_verrouillage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
