# Generated by Django 5.2.3 on 2025-11-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0005_merge_0004_donnees_note_colonne_0004_donnees_statut'),
        ('ansade_app', '0005_tableau_date_verrouillage'),
    ]

    operations = [
    ]
