# Generated by Django 5.2.3 on 2025-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0006_merge_20251122_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afficher_decimales', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='donnees',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
