# Generated by Django 5.2.3 on 2025-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0007_preferencesglobales_alter_donnees_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreferencesGlobales',
        ),
        migrations.AddField(
            model_name='tableau',
            name='afficher_decimales',
            field=models.BooleanField(default=False),
        ),
    ]
