# Generated by Django 5.2.3 on 2025-12-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0008_delete_preferencesglobales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='afficher_decimales',
            field=models.BooleanField(default=True),
        ),
    ]
