# Generated by Django 5.2.3 on 2026-01-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0009_alter_tableau_afficher_decimales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees',
            name='statut',
            field=models.CharField(blank=True, null=True),
        ),
    ]
