# Generated by Django 5.2.3 on 2026-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0010_alter_donnees_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneindicateur',
            name='est_pourcentage',
            field=models.BooleanField(default=False),
        ),
    ]
